[versions]

activity = "1.9.2"
lifecycleLivedataKtx = "2.6.2"
lifecycleViewmodelKtx = "2.6.2"
roomCompiler = "2.5.2"
roomRuntime = "2.5.2"
converterGson = "2.9.0"
loggingInterceptor = "4.11.0"
retrofit = "2.9.0"
picasso = "2.8"

[libraries]

androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit2-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }

[plugins]

